resources:
  - name: govwifi-product-page
    type: git
    source:
      uri: "https://github.com/alphagov/govwifi-product-page.git"
      branch: master

  - name: organisations-list-update
    type: s3
    source:
      bucket: govwifi-production-product-page-data
      versioned_file: organisations.yml
      region_name: eu-west-2

  - name: whitelisted-emails-update
    type: s3
    source:
      bucket: govwifi-production-product-page-data
      versioned_file: domains.yml
      region_name: eu-west-2

  - name: runner
    # See https://github.com/alphagov/govwifi-concourse-runner for a reference dockerfile
    # readonly_private_ecr_repo_url is provided by the hosted Concourse
    type: docker-image
    source:
      repository: "((readonly_private_ecr_repo_url))"
      tag: concourse-runner-latest

jobs:
  - name: deploy
    plan:
      - get: organisations-list-update
        trigger: true

      - get: whitelisted-emails-update
        trigger: true

      - get: src
        resource: govwifi-product-page
        trigger: true

      - get: runner

      - task: deploy
        privileged: true
        image: runner
        file: src/ci/tasks/deploy.yml
        params:
          CF_USER: ((govpaas-username))
          CF_PASS: ((govpaas-password))
