version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: puma
    versions:
    - 5.2.0
    - 5.2.1
  - dependency-name: capybara
    versions:
    - 3.35.1
    - 3.35.2
  - dependency-name: webdrivers
    versions:
    - 4.5.0
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: govuk-frontend
    versions:
    - 3.10.2
