---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: concourse/builder-task

params:
  REPOSITORY: govwifi/product-page
  TAG: latest
  CONTEXT: src

inputs:
  - name: src

outputs:
  - name: image

caches:
  - path: cache

run:
  path: build
